#!/bin/sh

echo "Downloading WordNet dictionaries"
# Use curl to download, as OS X doesn't include wget
curl -O http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz

echo "Copying WordNet dictionaries to test directory"
mkdir src/test/resources/wordnet
cd src/test/resources/wordnet
tar xvfz ../../../../wn3.1.dict.tar.gz
