# this script reads the output of the shell script generated by generate-agreement-sh-script.py
# overall stats about inter-annotator agreement are generated and written to a directory

'''
Expected format of agreement results file (by example)

Total pairs: 95
Matched: 65
Not Matched: 30
Accuracy: 0.684210526315789
        b       a       i       ii      s       v
b       7                                               
a               10              2               1       
i                       9                       1       
ii      3       1               17              2       
s                                       1       1       
v       12              2       5               21    
'''

import sys
import os

agmtResultsDir = sys.argv[1]
agmtStatsOutDir = sys.argv[2]
fnameToPairToInfo = {}
agmntResultsFnames = os.listdir(agmtResultsDir)

#get info
for _fname in agmntResultsFnames:
    print _fname
    items = _fname.split('.')
    fname = '.'.join(items[:-2])
    annotator1, annotator2 = items[-2], items[-1]
    annotatorPair = (annotator1, annotator2)
    annotationLines = open(agmtResultsDir + '/' + _fname).readlines()
    if annotationLines[0].startswith('Unknown'):
        print 'failed: ' + _fname
        continue
    if fname not in fnameToPairToInfo: fnameToPairToInfo[fname] = {}
    
    fnameToPairToInfo[fname][annotatorPair] = {'Total Pairs': int(annotationLines[0].split(':')[1].strip()),
                                                'Matched': int(annotationLines[1].split(':')[1].strip()),
                                                'Not Matched': int(annotationLines[2].split(':')[1].strip()),
                                                'Accuracy': float(annotationLines[3].split(':')[1].strip()),
                                                'Rest': annotationLines[4:]
                                                }


# average accuracy scores
total_results = 0
total_acc = 0
total_totalpairs = 0
total_matched = 0
total_pairs_no_dup = 0
total_pair_tokens_annotated = 0

for fname in fnameToPairToInfo:
    counted = False
    for annotatorPair in fnameToPairToInfo[fname]:
        if counted == False:
            total_pairs_no_dup += fnameToPairToInfo[fname][annotatorPair]['Total Pairs']
            counted = True
        total_results += 1
        total_acc += fnameToPairToInfo[fname][annotatorPair]['Accuracy']
        total_totalpairs += fnameToPairToInfo[fname][annotatorPair]['Total Pairs']
        total_pair_tokens_annotated += 2*fnameToPairToInfo[fname][annotatorPair]['Total Pairs']
        total_matched += fnameToPairToInfo[fname][annotatorPair]['Matched']

avg_acc = total_acc/float(total_results)
overall_acc = total_matched/float(total_totalpairs)

print avg_acc
print overall_acc
print total_pairs_no_dup
print total_totalpairs
print total_pair_tokens_annotated

out=open(agmtStatsOutDir + '/agreement_summary_stats.txt','w')
out.write('average accuracy: ' + str(avg_acc) + '\n')
out.write('overall accuracy: ' + str(overall_acc) + '\n')
out.write('total pairs annotated by anyone: ' + str(total_pairs_no_dup) + '\n')
out.write('total annotated pairs by two or more people: ' + str(total_totalpairs) + '\n')
out.write('total annotated pair tokens annotated outright: ' + str(total_pair_tokens_annotated))

out.close()

    
